services:
  valorease-web-app-node:
    container_name: valorease-web-app-node
    build:
      context: .
      dockerfile: dockerfile.node
    restart: no
    ports:
      - 3000:3000
    volumes:
      - .:/valorease-web-app:cached
      - /valorease-web-app/node_modules
      - /valorease-web-app/.next
    stdin_open: true
    tty: true
