FROM node:lts-alpine3.20

WORKDIR /valorease-web-app

COPY package*.json ./
COPY prisma ./prisma
COPY tsconfig.json ./

RUN npm install
RUN npm install -g prisma
RUN npm install -g next tsx typescript
RUN npm install --save-dev tslib @types/node

RUN npx prisma generate

COPY . .

RUN npx prisma migrate deploy

RUN npx tsx prisma/seed.ts

CMD "npx prisma generate && npm run build && next start -p 80"